// Adapter: BashoBot
// Schema version pinned to: uraimo/bashobot@v1.1.0
// Config format: Shell env (~/.bashobot/config.env)
// Pure Bash, zero runtime dependencies. Config is KEY=VALUE shell env file.
// BASHOBOT_LLM selects the provider enum; no model field (runtime /model cmd).
// Memory stored in ~/.bashobot/memory/ as markdown (not surfaced in config).

import type {
  Adapter,
  AdapterResult,
  CanonicalConfig,
  UnmappedField,
} from "../types.js";
import { makeParsePersona, makeWritePersona } from "../persona.js";

// Raw config is Record<string, string> (parsed from KEY=VALUE by loadConfig)
type BashoBotEnv = Record<string, string>;

// BASHOBOT_LLM enum → canonical provider
const LLM_TO_PROVIDER: Record<string, string> = {
  claude: "anthropic",
  openai: "openai",
  "openai-sub": "openai",
  gemini: "google",
  "gemini-sub": "google",
  "antigravity-sub": "anthropic",
};
const PROVIDER_TO_LLM: Record<string, string> = {
  anthropic: "claude",
  openai: "openai",
  google: "gemini",
};

export const BashoBotAdapter: Adapter = {
  cloneName: "bashobot",
  schemaVersion: "v1.1.0",
  configPatterns: ["config.env", ".bashobot/config.env"],
  defaultOutputFile: "config.env",

  write(config: CanonicalConfig): string {
    const llm = PROVIDER_TO_LLM[config.agent.provider] ?? config.agent.provider;

    const lines: string[] = [
      "# BashoBot configuration — generated by clawport",
      `BASHOBOT_LLM=${llm}`,
    ];

    if (config.agent.max_tokens !== undefined)
      lines.push(`MAX_CONTEXT_TOKENS=${config.agent.max_tokens}`);

    // system_prompt not configurable via env — flag it
    const allUnmapped = [
      ...config.unmapped,
      ...(config.agent.system_prompt !== undefined
        ? [
            {
              source_path: "agent.system_prompt",
              value: config.agent.system_prompt,
              reason:
                "bashobot system_prompt is hardcoded — set at runtime via /system command",
            },
          ]
        : []),
      ...(config.agent.temperature !== undefined
        ? [
            {
              source_path: "agent.temperature",
              value: config.agent.temperature,
              reason: "bashobot temperature is not configurable via config.env",
            },
          ]
        : []),
      ...config.skills.map((s) => ({
        source_path: `skills[${s.name}]`,
        value: s,
        reason: "bashobot tools are managed at runtime via /tools command",
      })),
    ];

    // Telegram channel
    const tgChannel = config.channels.find((c) => c.type === "telegram");
    if (tgChannel) {
      if (tgChannel.bot_token_env)
        lines.push(`TELEGRAM_BOT_TOKEN_ENV=${tgChannel.bot_token_env}`);
      else if (tgChannel.bot_token)
        lines.push(`TELEGRAM_BOT_TOKEN=${tgChannel.bot_token}`);
      if (tgChannel.chat_id)
        lines.push(`TELEGRAM_CHAT_ID=${tgChannel.chat_id}`);
    }
    for (const ch of config.channels) {
      if (ch.type !== "telegram")
        allUnmapped.push({
          source_path: `channels.${ch.type}`,
          value: ch,
          reason: "bashobot only supports telegram channel natively",
        });
    }

    if (allUnmapped.length > 0) {
      lines.push("");
      lines.push("# --- UNMAPPED FIELDS ---");
      for (const u of allUnmapped)
        lines.push(`# ${u.source_path}: ${u.reason}`);
    }

    return lines.join("\n") + "\n";
  },

  parse(_configPath: string, raw: unknown): AdapterResult {
    const env = raw as BashoBotEnv;
    const unmapped: UnmappedField[] = [];

    const llm = env.BASHOBOT_LLM ?? "";
    const provider = (LLM_TO_PROVIDER[llm] ?? llm) || "anthropic";

    // Flag API key env vars
    for (const key of [
      "ANTHROPIC_API_KEY",
      "GEMINI_API_KEY",
      "OPENAI_API_KEY",
    ]) {
      if (env[key] !== undefined)
        unmapped.push({
          source_path: key,
          value: env[key],
          reason: "API key — no canonical equivalent, set via environment",
        });
    }
    if (env.BASHOBOT_ALLOWED_DIRS !== undefined)
      unmapped.push({
        source_path: "BASHOBOT_ALLOWED_DIRS",
        value: env.BASHOBOT_ALLOWED_DIRS,
        reason: "no canonical equivalent",
      });

    const maxTokens = env.MAX_CONTEXT_TOKENS
      ? parseInt(env.MAX_CONTEXT_TOKENS, 10)
      : undefined;

    const agent = {
      name: "bashobot",
      model: "unknown", // set via /model at runtime
      provider,
      ...(maxTokens !== undefined &&
        !isNaN(maxTokens) && {
          max_tokens: maxTokens,
        }),
    };

    const channels = [];
    if (env.TELEGRAM_BOT_TOKEN || env.TELEGRAM_BOT_TOKEN_ENV) {
      channels.push({
        type: "telegram",
        bot_token: env.TELEGRAM_BOT_TOKEN,
        bot_token_env: env.TELEGRAM_BOT_TOKEN_ENV,
        chat_id: env.TELEGRAM_CHAT_ID,
        extra: {},
      });
    }

    return {
      ok: true,
      config: { agent, channels, memory: undefined, skills: [], unmapped },
    };
  },

  parsePersona: makeParsePersona("env", "agent.env"),

  writePersona: makeWritePersona("env", "agent.env"),
};
