// Adapter: MimiClaw
// Schema version pinned to: memovai/mimiclaw@v0.2.0
// Config format: Shell env provision template (.mimiclaw.env)
// C-based, bare-metal ESP32-S3 at ~0.5W. Config lives in mimi_secrets.h (C header)
// and NVS flash (provisioned via serial CLI). clawport writes a .mimiclaw.env
// template; users flash values via serial commands or rebuild firmware.
// Memory is via SOUL.md (persona) not a backend — maps to agent persona only.

import type {
  Adapter,
  AdapterResult,
  CanonicalConfig,
  UnmappedField,
} from "../types.js";
import { makeParsePersona, makeWritePersona } from "../persona.js";

type MimiClawEnv = Record<string, string>;

export const MimiClawAdapter: Adapter = {
  cloneName: "mimiclaw",
  schemaVersion: "v0.2.0",
  configPatterns: [".mimiclaw.env", "mimiclaw.env"],
  defaultOutputFile: ".mimiclaw.env",

  write(config: CanonicalConfig): string {
    const lines: string[] = [
      "# mimiclaw provision template — generated by clawport",
      "# Flash values via serial CLI: set_model_provider, set_model, set_tg_token",
      "# Or set in main/mimi_secrets.h and rebuild: idf.py fullclean && idf.py build",
      "",
      `MIMI_SECRET_MODEL_PROVIDER=${config.agent.provider}`,
      `MIMI_SECRET_MODEL=${config.agent.model}`,
    ];

    const tgChannel = config.channels.find((c) => c.type === "telegram");
    if (tgChannel) {
      lines.push("");
      if (tgChannel.bot_token_env)
        lines.push(`MIMI_SECRET_TG_TOKEN_ENV=${tgChannel.bot_token_env}`);
      else if (tgChannel.bot_token)
        lines.push(`MIMI_SECRET_TG_TOKEN=${tgChannel.bot_token}`);
    } else {
      lines.push("");
      lines.push("MIMI_SECRET_TG_TOKEN= # required — Telegram bot token");
    }

    lines.push("");
    lines.push("# Optional proxy settings");
    lines.push("MIMI_SECRET_PROXY_HOST=");
    lines.push("MIMI_SECRET_PROXY_PORT=");
    lines.push("");
    lines.push("# WiFi credentials — set manually");
    lines.push("MIMI_SECRET_WIFI_SSID=");
    lines.push("MIMI_SECRET_WIFI_PASS=");

    const allUnmapped = [
      ...config.unmapped,
      ...(config.agent.system_prompt !== undefined
        ? [
            {
              source_path: "agent.system_prompt",
              value: config.agent.system_prompt,
              reason:
                "mimiclaw uses SOUL.md for persona — write to agent.env persona file instead",
            },
          ]
        : []),
      ...(config.agent.temperature !== undefined
        ? [
            {
              source_path: "agent.temperature",
              value: config.agent.temperature,
              reason: "mimiclaw temperature is not configurable",
            },
          ]
        : []),
      ...(config.agent.max_tokens !== undefined
        ? [
            {
              source_path: "agent.max_tokens",
              value: config.agent.max_tokens,
              reason: "mimiclaw max_tokens is not configurable",
            },
          ]
        : []),
      ...(config.memory
        ? [
            {
              source_path: "memory",
              value: config.memory,
              reason: "mimiclaw has no memory backend config",
            },
          ]
        : []),
      ...config.channels
        .filter((c) => c.type !== "telegram")
        .map((ch) => ({
          source_path: `channels.${ch.type}`,
          value: ch,
          reason: "mimiclaw only supports Telegram channel",
        })),
      ...config.skills.map((s) => ({
        source_path: `skills[${s.name}]`,
        value: s,
        reason: "mimiclaw has no skills/tools support",
      })),
    ];

    if (allUnmapped.length > 0) {
      lines.push("");
      lines.push("# --- UNMAPPED FIELDS ---");
      for (const u of allUnmapped)
        lines.push(`# ${u.source_path}: ${u.reason}`);
    }

    return lines.join("\n") + "\n";
  },

  parse(_configPath: string, raw: unknown): AdapterResult {
    const env = raw as MimiClawEnv;
    const unmapped: UnmappedField[] = [];

    if (
      env.MIMI_SECRET_PROXY_HOST !== undefined &&
      env.MIMI_SECRET_PROXY_HOST !== ""
    )
      unmapped.push({
        source_path: "MIMI_SECRET_PROXY_HOST",
        value: env.MIMI_SECRET_PROXY_HOST,
        reason: "proxy config — no canonical equivalent",
      });
    if (
      env.MIMI_SECRET_PROXY_PORT !== undefined &&
      env.MIMI_SECRET_PROXY_PORT !== ""
    )
      unmapped.push({
        source_path: "MIMI_SECRET_PROXY_PORT",
        value: env.MIMI_SECRET_PROXY_PORT,
        reason: "proxy config — no canonical equivalent",
      });
    if (
      env.MIMI_SECRET_WIFI_SSID !== undefined &&
      env.MIMI_SECRET_WIFI_SSID !== ""
    )
      unmapped.push({
        source_path: "MIMI_SECRET_WIFI_SSID",
        value: env.MIMI_SECRET_WIFI_SSID,
        reason: "WiFi credentials — no canonical equivalent",
      });

    const agent = {
      name: "mimiclaw-agent",
      model: env.MIMI_SECRET_MODEL ?? "unknown",
      provider: env.MIMI_SECRET_MODEL_PROVIDER ?? "anthropic",
    };

    const channels = [];
    if (env.MIMI_SECRET_TG_TOKEN || env.MIMI_SECRET_TG_TOKEN_ENV) {
      channels.push({
        type: "telegram",
        bot_token: env.MIMI_SECRET_TG_TOKEN,
        bot_token_env: env.MIMI_SECRET_TG_TOKEN_ENV,
        extra: {},
      });
    }

    return {
      ok: true,
      config: { agent, channels, memory: undefined, skills: [], unmapped },
    };
  },

  parsePersona: makeParsePersona("env", "agent.env"),

  writePersona: makeWritePersona("env", "agent.env"),
};
