// Adapter: OpenGork
// Schema version pinned to: erenjugs/OpenGork@v0.1.0
// Config format: Shell env (.env)
// Shell-based uncensored agent. Supports two modes via OPENGORK_MODE:
// "local" (Ollama) or "xai" (Grok API). Sparse schema — no name, channels, memory.

import type {
  Adapter,
  AdapterResult,
  CanonicalConfig,
  UnmappedField,
} from "../types.js";
import { makeParsePersona, makeWritePersona } from "../persona.js";

type OpenGorkEnv = Record<string, string>;

export const OpenGorkAdapter: Adapter = {
  cloneName: "opengork",
  schemaVersion: "v0.1.0",
  configPatterns: [".env", ".opengork.env", "opengork.env"],
  defaultOutputFile: ".opengork.env",

  write(config: CanonicalConfig): string {
    const isXai = config.agent.provider === "xai";
    const lines: string[] = [
      "# OpenGork configuration — generated by clawport",
      `OPENGORK_MODE=${isXai ? "xai" : "local"}`,
    ];

    if (!isXai) {
      // local/Ollama mode
      lines.push(`OLLAMA_MODEL=${config.agent.model}`);
      if (
        config.agent.provider !== "ollama" &&
        config.agent.provider !== "local"
      )
        lines.push(
          `# provider: ${config.agent.provider} mapped to local Ollama mode`,
        );
    } else {
      lines.push(`# XAI_API_KEY: set in environment — not written to file`);
    }

    const allUnmapped = [
      ...config.unmapped,
      ...(config.agent.system_prompt !== undefined
        ? [
            {
              source_path: "agent.system_prompt",
              value: config.agent.system_prompt,
              reason: "opengork system_prompt is not configurable via .env",
            },
          ]
        : []),
      ...(config.agent.temperature !== undefined
        ? [
            {
              source_path: "agent.temperature",
              value: config.agent.temperature,
              reason: "opengork temperature is not configurable",
            },
          ]
        : []),
      ...(config.agent.max_tokens !== undefined
        ? [
            {
              source_path: "agent.max_tokens",
              value: config.agent.max_tokens,
              reason: "opengork max_tokens is not configurable",
            },
          ]
        : []),
      ...(config.memory
        ? [
            {
              source_path: "memory",
              value: config.memory,
              reason: "opengork has no memory backend config",
            },
          ]
        : []),
      ...config.channels.map((ch) => ({
        source_path: `channels.${ch.type}`,
        value: ch,
        reason: "opengork has no channel integration",
      })),
      ...config.skills.map((s) => ({
        source_path: `skills[${s.name}]`,
        value: s,
        reason: "opengork has no skills/tools config",
      })),
    ];

    if (allUnmapped.length > 0) {
      lines.push("");
      lines.push("# --- UNMAPPED FIELDS ---");
      for (const u of allUnmapped)
        lines.push(`# ${u.source_path}: ${u.reason}`);
    }

    return lines.join("\n") + "\n";
  },

  parse(_configPath: string, raw: unknown): AdapterResult {
    if (typeof raw !== "object" || raw === null || Array.isArray(raw))
      return { ok: false, error: "expected object config" };
    const env = raw as OpenGorkEnv;
    const unmapped: UnmappedField[] = [];

    const mode = env.OPENGORK_MODE ?? "local";
    const isXai = mode === "xai";

    if (env.XAI_API_KEY !== undefined)
      unmapped.push({
        source_path: "XAI_API_KEY",
        value: env.XAI_API_KEY,
        reason: "API key — no canonical equivalent, set via environment",
      });
    if (env.OLLAMA_BASE_URL !== undefined)
      unmapped.push({
        source_path: "OLLAMA_BASE_URL",
        value: env.OLLAMA_BASE_URL,
        reason: "no canonical equivalent",
      });
    if (env.OPENGORK_MODE !== undefined)
      unmapped.push({
        source_path: "OPENGORK_MODE",
        value: env.OPENGORK_MODE,
        reason: "no canonical equivalent — inferred as provider",
      });

    const agent = {
      name: "opengork",
      model: env.OLLAMA_MODEL ?? (isXai ? "grok-2" : "unknown"),
      provider: isXai ? "xai" : "ollama",
    };

    return {
      ok: true,
      config: { agent, channels: [], memory: undefined, skills: [], unmapped },
    };
  },

  parsePersona: makeParsePersona("env", "agent.env"),

  writePersona: makeWritePersona("env", "agent.env"),
};
