// Adapter: ZClaw
// Schema version pinned to: tnm/zclaw@v0.4.0
// Config format: Shell env provision template (.zclaw.env)
// C-based, runs on $5 ESP32 microcontroller. No traditional config file —
// credentials are provisioned via ./scripts/provision.sh. clawport writes
// a .zclaw.env provision template that users source before running provision.sh.
// Channels: Telegram only. No system_prompt, temperature, max_tokens.

import type {
  Adapter,
  AdapterResult,
  CanonicalConfig,
  UnmappedField,
} from "../types.js";
import { makeParsePersona, makeWritePersona } from "../persona.js";

type ZClawEnv = Record<string, string>;

export const ZClawAdapter: Adapter = {
  cloneName: "zclaw",
  schemaVersion: "v0.4.0",
  configPatterns: [".zclaw.env", "zclaw.env"],
  defaultOutputFile: ".zclaw.env",

  write(config: CanonicalConfig): string {
    const lines: string[] = [
      "# zclaw provision template — generated by clawport",
      "# Source this file then run: ./scripts/provision.sh",
      "#",
      "# zclaw runs on ESP32 — only provider, model, and Telegram are configurable.",
      "",
      `ZCLAW_PROVIDER=${config.agent.provider}`,
      `ZCLAW_MODEL=${config.agent.model}`,
    ];

    const tgChannel = config.channels.find((c) => c.type === "telegram");
    if (tgChannel) {
      lines.push("");
      if (tgChannel.bot_token_env)
        lines.push(`ZCLAW_TELEGRAM_TOKEN_ENV=${tgChannel.bot_token_env}`);
      else if (tgChannel.bot_token)
        lines.push(`ZCLAW_TELEGRAM_TOKEN=${tgChannel.bot_token}`);
      if (tgChannel.chat_id)
        lines.push(`ZCLAW_TELEGRAM_CHAT_ALLOWLIST=${tgChannel.chat_id}`);
    } else {
      lines.push("");
      lines.push(
        "ZCLAW_TELEGRAM_TOKEN=          # required — set before provisioning",
      );
      lines.push("ZCLAW_TELEGRAM_CHAT_ALLOWLIST= # comma-separated chat IDs");
    }

    lines.push("");
    lines.push("# WiFi credentials — set manually before provisioning");
    lines.push("ZCLAW_WIFI_SSID=");
    lines.push("ZCLAW_WIFI_PASS=");

    const allUnmapped = [
      ...config.unmapped,
      ...(config.agent.system_prompt !== undefined
        ? [
            {
              source_path: "agent.system_prompt",
              value: config.agent.system_prompt,
              reason: "zclaw system_prompt is hardcoded in firmware",
            },
          ]
        : []),
      ...(config.agent.temperature !== undefined
        ? [
            {
              source_path: "agent.temperature",
              value: config.agent.temperature,
              reason: "zclaw temperature is not configurable",
            },
          ]
        : []),
      ...(config.agent.max_tokens !== undefined
        ? [
            {
              source_path: "agent.max_tokens",
              value: config.agent.max_tokens,
              reason: "zclaw max_tokens is not configurable",
            },
          ]
        : []),
      ...(config.memory
        ? [
            {
              source_path: "memory",
              value: config.memory,
              reason: "zclaw has no memory backend config",
            },
          ]
        : []),
      ...config.channels
        .filter((c) => c.type !== "telegram")
        .map((ch) => ({
          source_path: `channels.${ch.type}`,
          value: ch,
          reason: "zclaw only supports Telegram channel",
        })),
      ...config.skills.map((s) => ({
        source_path: `skills[${s.name}]`,
        value: s,
        reason: "zclaw has no skills/tools support",
      })),
    ];

    if (allUnmapped.length > 0) {
      lines.push("");
      lines.push("# --- UNMAPPED FIELDS ---");
      for (const u of allUnmapped)
        lines.push(`# ${u.source_path}: ${u.reason}`);
    }

    return lines.join("\n") + "\n";
  },

  parse(_configPath: string, raw: unknown): AdapterResult {
    const env = raw as ZClawEnv;
    const unmapped: UnmappedField[] = [];

    if (env.ZCLAW_WIFI_SSID !== undefined && env.ZCLAW_WIFI_SSID !== "")
      unmapped.push({
        source_path: "ZCLAW_WIFI_SSID",
        value: env.ZCLAW_WIFI_SSID,
        reason: "WiFi credentials — no canonical equivalent",
      });
    if (env.ZCLAW_TELEGRAM_CHAT_ALLOWLIST !== undefined)
      unmapped.push({
        source_path: "ZCLAW_TELEGRAM_CHAT_ALLOWLIST",
        value: env.ZCLAW_TELEGRAM_CHAT_ALLOWLIST,
        reason: "chat allowlist — no canonical equivalent",
      });

    const agent = {
      name: "zclaw-agent",
      model: env.ZCLAW_MODEL ?? "unknown",
      provider: env.ZCLAW_PROVIDER ?? "anthropic",
    };

    const channels = buildChannels(env);

    return {
      ok: true,
      config: { agent, channels, memory: undefined, skills: [], unmapped },
    };
  },

  parsePersona: makeParsePersona("env", "agent.env"),

  writePersona: makeWritePersona("env", "agent.env"),
};

function buildChannels(env: ZClawEnv) {
  if (env.ZCLAW_TELEGRAM_TOKEN || env.ZCLAW_TELEGRAM_TOKEN_ENV) {
    return [
      {
        type: "telegram",
        bot_token: env.ZCLAW_TELEGRAM_TOKEN,
        bot_token_env: env.ZCLAW_TELEGRAM_TOKEN_ENV,
        extra: {},
      },
    ];
  }
  return [];
}
