// Watcher: Adapter Generator
// Given a cloned repo dir, detects its language, extracts the config schema,
// and emits a TypeScript adapter skeleton in src/adapters/<clone-name>.ts.
// Generated adapters mark every field as needing manual review —
// they are NOT auto-merged to main without a human PR review.

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { extractRustSchema } from "../extractors/rust.js";
import { extractTsSchema } from "../extractors/typescript.js";
import { extractPySchema } from "../extractors/python.js";
import { extractGoSchema } from "../extractors/go.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ADAPTERS_DIR = path.resolve(__dirname, "../../src/adapters");

export interface GeneratorInput {
  repoUrl: string;
  repoDir: string;
  headCommit: string;
  isNew: boolean;
}

type Language = "rust" | "typescript" | "python" | "go" | "unknown";

function detectLanguage(dir: string): Language {
  if (fs.existsSync(path.join(dir, "Cargo.toml"))) return "rust";
  if (fs.existsSync(path.join(dir, "package.json"))) return "typescript";
  if (
    fs.existsSync(path.join(dir, "pyproject.toml")) ||
    fs.existsSync(path.join(dir, "setup.py"))
  )
    return "python";
  if (fs.existsSync(path.join(dir, "go.mod"))) return "go";
  return "unknown";
}

function cloneNameFromUrl(repoUrl: string): string {
  // "https://github.com/owner/some-claw-thing" → "some-claw-thing"
  return (
    repoUrl
      .split("/")
      .pop()
      ?.toLowerCase()
      .replace(/[^a-z0-9-]/g, "-") ?? "unknown-clone"
  );
}

export async function generateAdapter(input: GeneratorInput): Promise<void> {
  const { repoUrl, repoDir, headCommit } = input;
  const cloneName = cloneNameFromUrl(repoUrl);
  const lang = detectLanguage(repoDir);
  const outFile = path.join(ADAPTERS_DIR, `${cloneName}.ts`);

  // If adapter already exists, write to a .generated.ts file for diff review
  const targetFile = fs.existsSync(outFile)
    ? path.join(ADAPTERS_DIR, `${cloneName}.generated.ts`)
    : outFile;

  const fields = extractFields(repoDir, lang);
  const skeleton = buildAdapterSkeleton({
    cloneName,
    repoUrl,
    headCommit,
    lang,
    fields,
  });

  fs.writeFileSync(targetFile, skeleton, "utf8");
  console.log(`[generator] Wrote adapter skeleton → ${targetFile}`);
  console.log(
    `[generator] Fields extracted: ${fields.length} — ALL marked for manual review`,
  );
}

interface FieldEntry {
  name: string;
  type_hint: string;
  optional: boolean;
  needs_review: boolean;
}

function extractFields(dir: string, lang: Language): FieldEntry[] {
  if (lang === "rust") {
    const schemas = extractRustSchema(dir);
    return schemas.flatMap((s) =>
      s.fields.map((f) => ({
        name: f.name,
        type_hint: f.rust_type,
        optional: f.optional,
        needs_review: f.needs_review,
      })),
    );
  }
  if (lang === "typescript") {
    const schemas = extractTsSchema(dir);
    return schemas.flatMap((s) =>
      s.fields.map((f) => ({
        name: f.name,
        type_hint: f.ts_type,
        optional: f.optional,
        needs_review: f.needs_review,
      })),
    );
  }
  if (lang === "python") {
    const schemas = extractPySchema(dir);
    return schemas.flatMap((s) =>
      s.fields.map((f) => ({
        name: f.name,
        type_hint: f.py_type,
        optional: f.optional,
        needs_review: f.needs_review,
      })),
    );
  }
  if (lang === "go") {
    const schemas = extractGoSchema(dir);
    return schemas.flatMap((s) =>
      s.fields.map((f) => ({
        name: f.name,
        type_hint: f.go_type,
        optional: f.optional,
        needs_review: f.needs_review,
      })),
    );
  }
  return [];
}

interface SkeletonInput {
  cloneName: string;
  repoUrl: string;
  headCommit: string;
  lang: Language;
  fields: FieldEntry[];
}

function buildAdapterSkeleton(input: SkeletonInput): string {
  const { cloneName, repoUrl, headCommit, lang, fields } = input;
  const varName = toPascalCase(cloneName) + "Adapter";

  const fieldLines = fields.map((f) => {
    const reviewTag = f.needs_review
      ? " // TODO: complex type — verify mapping"
      : "";
    const optTag = f.optional ? "?" : "";
    return `    ${f.name}${optTag}: unknown; // ${f.type_hint}${reviewTag}`;
  });

  const mappingLines = fields.map((f) => {
    const canonical = guessCanonicalPath(f.name);
    if (canonical) {
      return `      // ${f.name} → ${canonical}`;
    }
    return `      // UNMAPPED: ${f.name} (${f.type_hint}) — no canonical equivalent identified`;
  });

  return `// AUTO-GENERATED by clawport-watcher — DO NOT EDIT directly.
// Clone: ${cloneName} (${repoUrl})
// Schema version: ${headCommit}
// Language: ${lang}
// Generated: ${new Date().toISOString()}
//
// ACTION REQUIRED: Review all field mappings below before merging.
// Every "UNMAPPED" field must be explicitly resolved or flagged.

import type { Adapter, AdapterResult, UnmappedField } from "../types.js";

// Source config shape — auto-extracted from ${lang} source.
// Verify these types against the actual source before finalizing.
interface ${toPascalCase(cloneName)}Config {
${fieldLines.join("\n")}
}

export const ${varName}: Adapter = {
  cloneName: ${JSON.stringify(cloneName)},
  schemaVersion: ${JSON.stringify(headCommit)},
  configPatterns: ["config.yaml", "config.toml", "config.json"],

  parse(_configPath: string, raw: unknown): AdapterResult {
    const src = raw as ${toPascalCase(cloneName)}Config;
    const unmapped: UnmappedField[] = [];

    // TODO: implement exact field mapping. Skeleton field hints:
${mappingLines.join("\n")}

    // Replace this stub with actual mapping before merging.
    return {
      ok: false,
      error: "Adapter ${cloneName} is a generated skeleton — implement field mapping before use.",
    };
  },
};
`;
}

// Best-effort guess at which canonical field a source field name maps to.
// Returns null if no confident match — forces manual review.
function guessCanonicalPath(name: string): string | null {
  const exact: Record<string, string> = {
    name: "agent.name",
    model: "agent.model",
    provider: "agent.provider",
    system_prompt: "agent.system_prompt",
    temperature: "agent.temperature",
    max_tokens: "agent.max_tokens",
    bot_token: "channels[n].bot_token",
    guild_id: "channels[n].guild_id",
    chat_id: "channels[n].chat_id",
  };
  return exact[name] ?? null;
}

function toPascalCase(s: string): string {
  return s
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}
